// <auto-generated />
namespace TestLib.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class Car_TopSpeed : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201202221302479_Car_TopSpeed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/sozd50z4vJuNTgtAWefNRelwWGeHxOi/P3xOpnYdA6iPbHXXIYK/fXK9y7vSzj06y2m9ATX6v/Dr4gD56WVervG6vX+Xn7rWz2Ufp3fDVu9137Zvha+j/s4/Olu29vY/SF+uyzCYlfXCelU3+Ubr69NHrtqrzz/NlXmdtPnuZtW1e07yczXLGX+nwaPXp7Ujx8O7OHkhxN1suqzZraZJ7uHcwfVJny9nNuG4G8iq/KJq25g5frBeTvDbwXrc1seBH6bPiXT57ni8v2rmF+UX2znzy6UfpV8uC+JVeaet1/t4YvKlWr1d5PjwOgdoB8iK7LC4Y6xhVPkpf5SV/28yLlXDmmGb299dvn9XV4lUF4PbD3/91ta6n1NGbqvvNm6y+yNsQhcd3HZ9u5F7p8Wvwr53e9+XgW/LF/yt4GP++J8Pt7bw3xw0yC81x83V4xXBEn1cMF92GV46bppoW3LXDR7sNB3C6nKWD/CrEU6yJVOuyLVZlMaUeP/voWz1ixGDZ8ThYOvoQ2m6IF0H7cvk0L/M2T4+nGAeANtNs1p8DosEs/IRYPa/BaVlJ5gdKqFi2fbkoltNilZVDOHdeeB9RAlYWfvebp/kqX0IQhgj/gR1b+B0y3USVx3c9tulrHnqnpTfy2uNwfJa/65BK27/O20AWHKf6PNVjofBVHmbsZWWizuveAILujcR53/fEsUvHTZJh0TSD683CJlnw3jbj67J0OJCIxNvZsN89visOlX7w+O6A5/X4i2y1InXoeWL6Sfpa3LCT7dfv72wtBMbdaRPxuSy2tieyD9lF3vmWuiZMnxV10z7N2mySQeOezBb9ZjfznunJY8H+HBmmMo3xu/oOHVeUubUvmPriMxrMAhLNdi/kjv5bKXzfrMzquIN4UpXrxXKDq7kJhtULPpRBZTEMJ+a9+SBj398euvPMfJju0z6kx3c7pO6pvd5s9qxEyBm34huVzw/inKh6uQXvDLz3sz3z4jj5QOSTH/Kc9BRdt4nt3Sq8jmJ7rEom0H5pLO7saR1p8lFKpLksZtA4r6+bNl+M0WD8+heVJ2VB43UNvsiWxTlN/JvqbY4YmpTi1w9erbfbNLPy/7URbIHx3+jnv2fI1okwuI/3BDEcdy4vs3o6Z082iDLfs4NuWNlBsh9U/n8novtZmVNRHxumAHHXRpjfZJijnuAPNR4JnMH3j6u+VjgzZHVuzTwYyfvEMB/alwXZoeY3Hbb0PMzuXPWCl6HYRazEZx/NJhVNqnBvLByIRzXDQU0M7kCg8LMT8AT4eb7IDWFONy762Qlr+ladeGS9tDln4s2muHAgkIFe5tOAO2ybs+V5Zbi0g5Fp0tFmX+RtNiPWOa7b4jybtvT1NG8azi/9ZFauqckpGZ3Z2fLLdbtatzTkfDEpr31igNk39c+xW4jz4y9XnEi65RA2DoHQLGgI+ZfLJ+uinFm8n0U07wAISJGaCMwlzG1+cW0hvaiWtwSk5HtqhP9NvlhRzixvvly+zi7zYdxupmFIscdPi+yizhY+BeUTxeR1Rj17XVAH/huuP/qT2JUWPI7+nwAAAP//xUE5emUZAAA="; }
        }
    }
}
