// <auto-generated />
namespace TestLib.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ShapeAnimationPath : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ShapeAnimationPath));
        
        string IMigrationMetadata.Id
        {
            get { return "201209251802192_ShapeAnimationPath"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
