// <auto-generated />
namespace TestLib.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class IX_Car_BrandId : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201202201920484_IX_Car_BrandId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/sozd50z4vJuNTgtAWefNRelwWGeHxOi/P3xOpnYdA6iPbHXXIYK/fXK9y7vSzj06y2m9ATX6v/Dr4gD56WVervG6vX+Xn7rWz2Ufp3fDVu9137Zvha+j/s4/Olu29vY/SF+uyzCYlfXCelU3+Ubr69NHrtqrzz/NlXmdtPnuZtW1e07yczXLGX+nwaPXp7Ujx8O7OHkhxN1suqzZraZJ7uHcwfVJny9nNuG4G8iq/KJq25g5frBeTvDbwXrc1seBH6bPiXT57ni8v2rmF+UX2znzy6UfpV8uC+JVeaet1fjMGL7LL4oI7jA3oo/RVXvK3zbxYCVONaVJ+f/32WV0tXlWAbj/8/V9X63pKHb2put+8yeqLvA1ReHzXsdhGxpMevwbr2Zl5X+a75ZT+v4L98O978srezjfHLDTHzdfhFcMRfV4xXHQbXjlummpacNcOH+02HMDpcpYO8qsQT7EmUq3LtliVxZR6/Oyjb/WIEYNlx+Ng6ehDaLshXgTty+XTvMzbPD2eYhwA2kyzWX8OiAaz8BNi9bwGp2UlWQ7oj2LZ9uWiWE6LVVYO4dx54X1ECVhZ+N1vnuarfAlBGCL8B3Zs4XfIdBNVHt/12Kaveeidlt7Ia4/D8Vn+rkMqbf86bwNZcJzq81SPhcJXeZixl5WJOq97Awi6NxLnfd8Txy4dN0mGRdMMrjcLm2TBe9uMr8vS4UAiEm9nw373+K74QvrB47sDTtPjL7LVitSh50TpJ+lr8aBOtl+/v5+0EBh3p03EXbLY2p7IPmQXeedb6powfVbUTfs0a7NJBo17Mlv0m93Me6YnjwX7c2SYyjTG7/JC14tkbu0Lpr74jAazgESz3Qu5o/9WCrc1K7M67tudVOV6sdzgJW6CYfWCD2VQWQzDiTlePsjY933oj+92CNRTVr056On2cD5vNdsqVR8031GlcIsZH3jvZ3u+xN3xgcgnP+Q56amnbhPbu1VTHXX0WFVDoLPSWKDX0xXS5KOUSHNZzKAnXl83bb4Yo8H49S8qT8qCxusafJEti3Oa+DfV2xxBK6myrx8tWh+1aWbl/2tDxgLjv9E7f88orRMXcB/vCWI40FteZvV0zv5nENZt7OD/O0HUz8qEiOxvoB9Cna9FwK8TWajz9UMNAQL/6/1Dma8VQQyZjFszD0byPmHDh/ZlQXao+U1HCj2nrjtXvXhhKFwQFf/ZR7NJRZMq3BvzwOOBxHAcEYM74Jv/7MQYAX6eI3FDZNENRX52Iom+SSYeWS9thpZ4sykuHAjka5f5NOAO2+ZseV4ZLu1gZJp0tNkXeZvNiHWO67Y4z6YtfT3Nm4ZTOj+ZlWtqckoWY3a2/HLdrtYtDTlfTMprnxhg9k39c7gU4vz4yxXnbr6JIRCaBQ0h/3L5ZF2UM4v3s4jmHQABKVITgbmErcwvri2kF9XyloCUfE+N8L/JFytKU+XNl8vX2WXucOvidjMNQ4o9flpkF3W28CkonygmrzPq2euCOvDfcP3Rn8SutDxw9P8EAAD//2tH7OqTGAAA"; }
        }
    }
}
