// <auto-generated />
namespace TestLib.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class Car_Color : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201202221335547_Car_Color"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/sozd50z4vJuNTgtAWefNRelwWGeHxOi/P3xOpnYdA6iPbHXXIYK/fXK9y7vSzj06y2m9ATX6v/Dr4gD56WVervG6vX+Xn7rWz2Ufp3fDVu9137Zvha+j/s4/Olu29vY/SF+uyzCYlfXCelU3+Ubr69NHrtqrzz/NlXmdtPnuZtW1e07yczXLGX+nwaPXp7Ujx8O7OHkhxN1suqzZraZJ7uHcwfVJny9nNuG4G8iq/KJq25g5frBeTvDbwXrc1seBH6bPiXT57ni8v2rmF+UX2znzy6UfpV8uC+JVeaet1/t4YvKlWr1d5PjwOgboZyElVVu+L+d7Oe6P+IrssLphWsbn4KH2Vl/xtMy9WIg9j4qffX799VleLVxWg2w9//9fVup5SR2+q7jdvsvoib0MUHt910rFRZqTHryE1lqneV25uyY3/r5Ac/PtzyCw0x83X4RXDEX1eMVx0G145bppqWnDXDh/tNhzA6XKWDvKrEE+xJlKty7ZYlcWUevzso2/1iBGDZcfjYOnoQ2i7IV4E7cvl07zM2zw9nmIcANpMs1l/DogGs/ATYvW8BqdlJRk9qL5i2fblolhOi1VWDuHceeF9RAlYWfjdb57mq3wJQRgi/Ad2bOF3yHQTVR7f9dimr3nonZbeyGuPw/FZ/q5DKm3/Om8DWXCc6vNUj4XCV3mYsZeViTqvewMIujcS533fE8cuHTdJhkXTDK43C5tkwXvbjK/L0uFAIhJvZ8N+9/iuuHH6weO7A/7e4y+y1YrUoef/6Sfpa3H+TrZfv7+LtxAYd6dNxNOz2NqeyD5kF3nnW9j4Wf6sqJv2adZmkwwa92S26De7mfdMTx4L9ufIMJVpjN/VY+k4wMytfcHUF5/RYBaQaLZ7IXf030rhcWdlVsfdUvJz1ovlBgd3EwyrF3wog8piGE7MZ/RBxr6/PXTnD/ow3ae3h6ROYUAz+agP4/HdznT1VGePIzpi2eWuW/GeyvgHcV9URd2C/wbe+9nmHnG+fCDyyQ95TnrKstvE9m6VZkc5PlZFFWhQHnU3Yu5pLmnyUUqkuSxm0Fqvr5s2X4zRYPz6F5UnZUHjdQ2+yJbFOU38m+ptjuifFOvXD7utx9w0s/L/tbF3gfHfGCu8Z7DZiVK4j/cEMRwxLy+zejpnbziIj9+zg25A3EHyvcPhKFqIZzbi9f+dUPNnhVFEJ/1sEPDrxF/qov5QA6XAS33/gO9rxVlDpuzWzIORvE9w9aF9WZAdan7T8VTP9e3OVS+qGgqqxPR89tFsUtGkCvfG4pR4uDUcbcXgDkQwPzuRWICf5+DcEH91A7afnXir7yoQj6yXNgVPvNkUFw4EEvLLfBpwh21ztjyvDJd2MDJNOtrsi7zNZsQ6x3VbnGfTlr6e5k3Dia+fzMo1NTklSzY7W365blfrloacLybltU8MMPum/jmoDHF+/OWKM1zfxBAIzYKGkH+5fLIuypnF+1lE8w6AgBSpicBcwobnF9cW0otqeUtASr6nRvjf5IsVJfPy5svl6+wyH8btZhqGFHv8tMgu6mzhU1A+UUxeZ9Sz1wV14L/h+qM/iV1p/efo/wkAAP//qa9yr3QaAAA="; }
        }
    }
}
