<?xml version="1.0" encoding="utf-8"?><Database Name="test" ContextNamespace="TestLib" Class="DBContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=test;Integrated Security=True" SettingsObjectName="TestLib.Properties.Settings" SettingsPropertyName="testConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Cars" Member="Cars">
    <Type Name="Car">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="RegistrationNumber" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MadeIn" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Car_FrequentDriver" Member="FrequentDrivers" ThisKey="ID" OtherKey="CarID" Type="FrequentDriver" />
    </Type>
  </Table>
  <Table Name="dbo.Persons" Member="Persons">
    <Type Name="Person">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="SSN" Type="System.String" DbType="Char(12) NOT NULL" CanBeNull="false" />
      <Column Name="PersonKey" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SexID" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="DisplayName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PersonStatus" Type="PersonStatus" DbType="TinyInt" CanBeNull="true" />
      <Association Name="Person_FrequentDriver" Member="FrequentDrivers" ThisKey="ID" OtherKey="PersonID" Type="FrequentDriver" />
    </Type>
  </Table>
  <Table Name="dbo.FrequentDrivers" Member="FrequentDrivers">
    <Type Name="FrequentDriver">
      <Column Name="CarID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PersonID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Car_FrequentDriver" Member="Car" ThisKey="CarID" OtherKey="ID" Type="Car" IsForeignKey="true" />
      <Association Name="Person_FrequentDriver" Member="Person" ThisKey="PersonID" OtherKey="ID" Type="Person" IsForeignKey="true" />
    </Type>
  </Table>
</Database>